#https://cloud.google.com/sdk/gcloud/reference/functions/deploy
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'tester1', '--allow-unauthenticated', '--trigger-http', '--runtime', 'python39', '--entry-point', 'scrape', '--region', 'asia-northeast1']
  dir: 'cloudfcn'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'tester2', '--allow-unauthenticated', '--trigger-http', '--runtime', 'python39', '--entry-point', 'scrape', '--region', 'asia-northeast1']
  dir: 'cloudfcn'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'tester3', '--allow-unauthenticated', '--trigger-http', '--runtime', 'python39', '--entry-point', 'scrape', '--region', 'asia-northeast1']
  dir: 'cloudfcn'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'tester4', '--allow-unauthenticated', '--trigger-http', '--runtime', 'python39', '--entry-point', 'scrape', '--region', 'asia-northeast1']
  dir: 'cloudfcn'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'tester5', '--allow-unauthenticated', '--trigger-http', '--runtime', 'python39', '--entry-point', 'scrape', '--region', 'asia-northeast1']
  dir: 'cloudfcn'



